---
title: "events - 模块研究"
date: "2020-02-04"
permalink: "notes/2020-02-04-nodejs-events"
---

⚡<strong>「内容速览」</strong>⚡

- 异步事件驱动模型
- events
- 错误事件的处理


### 异步事件驱动模型
Node.js 使用了一个事件驱动、异步非阻塞 I/O 的模型，使其轻量又高效。

  - 阻塞I/O和非阻塞I/O：
  一个I/O操作主要包括磁盘寻道,读取数据,复制数据到内存。

  阻塞I/O：在发起I/O操作之后，进程就会被阻塞，直到数据准备完成并复制到用户空间，返回响应或超时，进程才会解除block的状态。
  非阻塞I/O：在发起I/O操作之后，函数返回，进程继续执行，不断轮询需要获取的数据是否准备好了，如果准备好了则阻塞进程去内核中复制数据。
  
  阻塞I/O和非阻塞I/O都需要阻塞进程。

  - 同步I/O和异步I/O：
  同步I/O指进行I/O操作都会阻塞process直至获得响应或超时，因此阻塞I/O，非阻塞I/O，IO多路复用I/O都是同步I/O。
  异步I/O指进行I/O操作不会造成任何的阻塞，当I/O操作完成返回响应时，以事件的形式通知执行IO操作的进程。

  ![IO](~@images/nodejs/IO.png)


  - 事件驱动
  事件驱动(event-driven)就是通过监听事件的状态变化来做出相应的操作。比如读取一个文件，文件读取完毕，或者文件读取错误，那么就触发对应的状态，然后调用对应的回掉函数来进行处理。

  nodejs通过事件循环(event-loop)来循环取出消息队列(event-queue)中的消息进行处理，消息队列就是当一个事件状态发生变化时，就将一个消息压入队列中。处理过程基本上就是去调用该消息对应的回调函数。

### events
大多数 Node.js 核心 API 构建于惯用的异步事件驱动架构，其中某些类型的对象（又称触发器，Emitter）会触发命名事件来调用函数（又称监听器，Listener）。

所有能触发事件的对象都是 EventEmitter 类的实例。 当 EventEmitter 对象触发一个事件时，所有绑定在该事件上的函数都会被同步地调用。

eventEmitter.on() 用于注册监听器， eventEmitter.emit() 用于触发事件。

```js
const EventEmitter = require('events');

class MyEmitter extends EventEmitter {}

const myEmitter = new MyEmitter();

myEmitter.on('event', () => {
  console.log('event emit!');
})

myEmitter.emit('event');
```

### 错误事件的处理
当 EventEmitter 实例出错时，应该触发 'error' 事件。 这些在 Node.js 中被视为特殊情况。

如果没有为 'error' 事件注册监听器，则当 'error' 事件触发时，会抛出错误、打印堆栈跟踪、并退出 Node.js 进程。为了防止崩溃 Node.js 进程，可以为 'error' 事件注册监听器。

```js
const myEmitter = new MyEmitter();
myEmitter.on('error', (err) => {
  console.error('error：' + err.message);
});
myEmitter.emit('error', new Error('错误'));
// 打印: 错误信息
```

但是上面的代码只能捕获到Error，无法捕获到Exception，例如：

  - Error(错误)表示系统级的错误和程序不必处理的异常，例如代码在编译的时候就出现了错误、内存资源不足等对于这种错误，程序基本无能为力，除了退出运行外别无选择。

  - Exception(违例)表示需要捕捉或者需要程序进行处理的异常，比如对象中某个属性不存在，或者是数据类型不对。代码可以继续执行，不过会在控制台中输出一段错误。

```js
myEmitter.on('test', () => {
  // num是一个不存在的变量，错误并没有被捕获
  console.log(num) // ReferenceError: num is not defined
})
myEmitter.emit('test')
```

利用try，catch我们能够同时捕获error和exceoption
```js
MyEmitter.prototype._emit = function(name, ...args) {
  try {
    return this.emit(name, ...args);
  } catch (error) {
    return this.emit('error', error);
  }
}
```

参考链接：

[Node.js - events](http://nodejs.cn/api/events.html)









  

  


